#!/bin/bash

pod() {
echo $CI_JOB_ID
###clone e2e-konvoy-repo
echo "cloning e2e-konvoy repo*************"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'git clone https://github.com/openebs/e2e-konvoy.git'
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-konvoy && git checkout openebs-localpv && bash openebs-konvoy-e2e/pipelines/stages/5-cleanup/4LD02-cluster-cleanup/cluster-cleanup node '"'$CI_JOB_ID'"'' '"'$master_ip'"' '"'$worker1_ip'"' '"'$worker2_ip'"' '"'$worker3_ip'"' '"'$worker4_ip'"' '"'$worker5_ip'"' '"'$master_name'"' '"'$worker1_name'"' '"'$worker2_name'"' '"'$worker3_name'"' '"'$worker4_name'"' '"'$worker5_name'"' '"'$master_ip1'"' '"'$master_ip2'"' '"'$master_name1'"' '"'$master_name2'"'
}

node() {
job_id=$(echo $1)

git clone https://github.com/openebs/e2e-tests.git
cd e2e-tests

# Replace the VM IP In csv file
sed -i -e 's/10.12.22.10/10.43.1.110/g' \
-e 's/10.12.22.11/10.43.1.111/g' \
-e 's/10.12.22.12/10.43.1.112/g' \
-e 's/10.12.22.13/10.43.1.113/g' k8s/on-prem/openshift-installer/ip.csv

sed -i '/10.43.1.113/a \
10.43.1.114 \
10.43.1.115' k8s/on-prem/openshift-installer/ip.csv

#Replace the VM names in csv file
sed -i -e 's/auto1/d2iq-master/g' \
-e 's/auto2/d2iq-node1/g' \
-e 's/auto3/d2iq-node2/g' \
-e 's/auto4/d2iq-node3/g' k8s/on-prem/openshift-installer/vm_name.csv

sed -i '/d2iq-node3/a \
d2iq-node4 \
d2iq-node5' k8s/on-prem/openshift-installer/vm_name.csv

#Replace the snapshot name and exp ip in vars
sed -i -e 's/snapshot_name: "oc-cluster"/snapshot_name: "konvoy"/g' \
-e 's/esx_ip: "10.12.1.1"/esx_ip: "10.43.1.1"/g' k8s/on-prem/openshift-installer/vars.yml

ansible-playbook k8s/on-prem/openshift-installer/revert_cluster_state.yml -vv

#Removimg e2e openshift test repo
cd  && rm -rf e2e-konvoy 
}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11} ${12} ${13} ${14} ${15} ${16} ${17} ${18}
else
  pod
fi
