#!/bin/bash
set -x

#################
## ENVIRONMENT ##
#################

## https://github.com/openebs/litmus/blob/master/apps/percona/chaos/openebs_target_network_delay/test_vars.yml
test_name=$(${utils_path}/generate_test_name testcase=openebs-target-network-delay metadata="")

###################
## DEPENDENCIES  ##
###################

${utils_path}/setup_dependencies litmus-test

## Clone the litmus repo, checkout the e2e branch, navigate to litmus root 

git clone https://github.com/litmuschaos/litmus.git
cd litmus

############################
## LITMUS PRECONDITIONING ##
############################

: << EOF
  ----------------------------------------------------------------------------------
 | specAttribute        | kind     | percona             | mongodb                  |
  ----------------------------------------------------------------------------------|
 | appLabel             | env      | name=percona        | app=pgset                |
 | pvcName              | env      | percona-mysql-claim | pgdata-claim-pgset-0     | 
  ----------------------------------------------------------------------------------
EOF

cp experiments/chaos/openebs_target_network_delay/run_litmus_test.yml run_test.yml

sed -i -e 's/''name=percona''/''app=pgset''/g' \
-e 's/value: app-percona-ns/value: app-pgres-ns/g' \
-e 's/value: percona-mysql-claim/value: pgdata-claim-pgset-0/g' run_test.yml


#################
## RUNNER MAIN ##
#################

## TODO: Keep testnames & label names similar & keep keys consistent for a type of test
echo "Running the litmus test.."
${utils_path}/litmus_job_runner label='name:openebs-target-network-delay' job=run_test.yml
${utils_path}/task_delimiter;

echo "Dumping state of cluster post job run"; echo ""
${utils_path}/dump_cluster_state;
${utils_path}/task_delimiter;

#################
## GET RESULT  ##
#################

## Check the test status & result from the litmus result custom resource
${utils_path}/get_litmus_result ${test_name}

