#!/bin/bash


pod() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-konvoy && bash openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/RUTT-cvr-scaleup/cvr-scaleup node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$RELEASE_TAG'"'
}

node() {
job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
releaseTag=$(echo $4)
case_id=RUTT

source ~/.profile
gittoken=$(echo "$github_token")

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

bash openebs-konvoy-e2e/utils/pooling jobname:cvr-migration
bash openebs-konvoy-e2e/utils/e2e-cr jobname:cvr-scaleup jobphase:Waiting
bash openebs-konvoy-e2e/utils/e2e-cr jobname:cvr-scaleup jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag"

################
# LitmusBook 1 #
################

test_name=$(bash openebs-konvoy-e2e/utils/generate_test_name testcase=busybox-provision-cvr-scaleup-ns metadata="")
echo $test_name

cd litmus
echo "Running the litmus test for Busybox Deployment.."
# copy the content of deployer run_litmus_test.yml into a different file to update the test specific parameters.
cp apps/busybox/deployers/run_litmus_test.yml busybox_cvr_scaleup.yml

sed -i -e 's/app: busybox-litmus/app: deploy-busybox-cvr-scaleup/g' \
-e 's/generateName: litmus-busybox-deploy-/generateName: litmus-busybox-deploy-cvr-scaleup-/g' \
-e 's/app=busybox-sts/app=bb-cvr-scaleup/g' \
-e 's/value: statefulset/value: deployment/g' \
-e 's/value: openebs-cstor-sparse/value: openebs-cstor-cvr-scale/g' \
-e 's/value: openebs-busybox/value: openebs-bb-cvr-scaleup/g' \
-e 's/value: app-busybox-ns/value: cvr-scaleup-ns/g' busybox_cvr_scaleup.yml

cat busybox_cvr_scaleup.yml

# Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.

bash ../openebs-konvoy-e2e/utils/litmus_job_runner label='app:deploy-busybox-cvr-scaleup' job=busybox_cvr_scaleup.yml
cd ..
# Get the cluster state Once the litmus jobs completed.
bash openebs-konvoy-e2e/utils/dump_cluster_state;
# Update the e2e event for the job.
bash openebs-konvoy-e2e/utils/event_updater jobname:cvr-scaleup $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
python3 openebs-konvoy-e2e/utils/result/result_update.py $job_id RUTT 3-functional "Verify the CVR scaled up successfully from one pool to another pool and check the volume status is healthy" $testResult $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# LitmusBook 2 #
################

run_id="cvr-scaleup";test_name=$(bash openebs-konvoy-e2e/utils/generate_test_name testcase=busybox-liveness metadata=${run_id})
echo $test_name

cd litmus
cp apps/busybox/liveness/run_litmus_test.yml busybox_loadgen_cvr_scaleup.yml

sed -i -e 's/value: app-busybox-ns/value: cvr-scaleup-ns/g' \
-e 's/app=busybox-sts/app=bb-cvr-scaleup/g' \
-e 's/liveness: litmus-busybox-liveness/liveness: bb-liveness-cvr-scaleup/g' busybox_loadgen_cvr_scaleup.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' busybox_loadgen_cvr_scaleup.yml

cat busybox_loadgen_cvr_scaleup.yml

bash ../openebs-konvoy-e2e/utils/litmus_job_runner label='liveness:bb-liveness-cvr-scaleup' job=busybox_loadgen_cvr_scaleup.yml
cd ..
bash openebs-konvoy-e2e/utils/dump_cluster_state;
bash openebs-konvoy-e2e/utils/event_updater jobname:cvr-scaleup $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
python3 openebs-konvoy-e2e/utils/result/result_update.py $job_id RUTT 3-functional "Verify the CVR scaled up successfully from one pool to another pool and check the volume status is healthy" $testResult $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# LitmusBook 3 #
################

test_name=$(bash openebs-konvoy-e2e/utils/generate_test_name testcase=openebs-cvr-scaleup metadata="")
echo $test_name

cd litmus
cp experiments/functional/cvr-scaleup/run_litmus_test.yml cvr_scaleup.yml

 # Update the environmental variables in litmus job spec.

sed -i -e '/name: SPC_NAME/{n;s/.*/            value: cstor-block-disk-pool-stripe/}' \
-e '/name: OPENEBS_VERSION/{n;s/.*/            value: '"'$releaseTag'"'/}' \
-e '/name: APP_PVC/{n;s/.*/            value: openebs-bb-cvr-scaleup/}' \
-e '/name: OPERATOR_NAMESPACE/{n;s/.*/            value: openebs/}' \
-e '/name: APP_LABEL/{n;s/.*/            value: 'app=bb-cvr-scaleup'/}' \
-e '/name: APP_NAMESPACE/{n;s/.*/            value: cvr-scaleup-ns/}' \
-e '/name: DATA_PERSISTENCE/{n;s/.*/            value: busybox/}' \
-e 's/name: cvr-scaleup/name: cvr-scaleup-configmap/g' cvr_scaleup.yml

## Insert the set of variables for busybox data consistency util into configmap spec.
sed -i '/parameters.yml: |/a \
    blocksize: 4k \
    blockcount: 1024 \
    testfile: cvrscaleup
' cvr_scaleup.yml

cat  cvr_scaleup.yml
 # Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../openebs-konvoy-e2e/utils/litmus_job_runner label='app:cvr-scaleup' job=cvr_scaleup.yml
cd ..
# Get the cluster state Once the litmus jobs completed.
bash openebs-konvoy-e2e/utils/dump_cluster_state;
bash openebs-konvoy-e2e/utils/event_updater jobname:cvr-scaleup $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
python3 openebs-konvoy-e2e/utils/result/result_update.py $job_id RUTT 3-functional "Verify the CVR scaled up successfully from one pool to another pool and check the volume status is healthy" $testResult $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# LitmusBook 4 #
################

run_id="deprovision-cvr-scaleup";test_name=$(bash openebs-konvoy-e2e/utils/generate_test_name testcase=busybox-liveness metadata=${run_id})
echo $test_name

cd litmus
cp apps/busybox/liveness/run_litmus_test.yml busybox_loadgen_deprovision_cvr_scaleup.yml

sed -i -e 's/value: app-busybox-ns/value: cvr-scaleup-ns/g' \
-e 's/app=busybox-sts/app=bb-cvr-scaleup/g' \
-e 's/value: provision/value: deprovision/g' \
-e 's/liveness: litmus-busybox-liveness/liveness: bb-liveness-deprovision-cvr-scaleup/g' busybox_loadgen_deprovision_cvr_scaleup.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' busybox_loadgen_deprovision_cvr_scaleup.yml

cat busybox_loadgen_deprovision_cvr_scaleup.yml

bash ../openebs-konvoy-e2e/utils/litmus_job_runner label='liveness:bb-liveness-deprovision-cvr-scaleup' job=busybox_loadgen_deprovision_cvr_scaleup.yml
cd ..
bash openebs-konvoy-e2e/utils/dump_cluster_state;
bash openebs-konvoy-e2e/utils/event_updater jobname:cvr-scaleup $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
python3 openebs-konvoy-e2e/utils/result/result_update.py $job_id RUTT 3-functional "Verify the CVR scaled up successfully from one pool to another pool and check the volume status is healthy" $testResult $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# LitmusBook 5 #
################

test_name=$(bash openebs-konvoy-e2e/utils/generate_test_name testcase=busybox-deprovision-cvr-scaleup-ns metadata="")
echo $test_name

cd litmus
echo "Running the litmus test for Busybox deprovision.."
cp apps/busybox/deployers/run_litmus_test.yml busybox_deprovision_cvr_scaleup.yml

sed -i -e 's/app: busybox-litmus/app: deprovision-busybox-cvr-scaleup/g' \
-e 's/generateName: litmus-busybox-deploy-/generateName: litmus-busybox-deprovision-cvr-scaleup-/g' \
-e 's/app=busybox-sts/app=bb-cvr-scaleup/g' \
-e 's/value: statefulset/value: deployment/g' \
-e 's/value: provision/value: deprovision/g' \
-e 's/value: openebs-cstor-sparse/value: openebs-cstor-cvr-scale/g' \
-e 's/value: openebs-busybox/value: openebs-bb-cvr-scaleup/g' \
-e 's/value: app-busybox-ns/value: cvr-scaleup-ns/g' busybox_deprovision_cvr_scaleup.yml

cat busybox_deprovision_cvr_scaleup.yml

# Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.

bash ../openebs-konvoy-e2e/utils/litmus_job_runner label='app:deprovision-busybox-cvr-scaleup' job=busybox_deprovision_cvr_scaleup.yml
cd ..
# Get the cluster state Once the litmus jobs completed.
bash openebs-konvoy-e2e/utils/dump_cluster_state;
# Update the e2e event for the job.
bash openebs-konvoy-e2e/utils/event_updater jobname:cvr-scaleup $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

rc_val=$(echo $?)

# Obtain the status of the test using litmusresult(lr) 
testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)
current_time=$(eval $time)

# Update the result of the test case in github mayadata-io/e2e-openshift repository.
if [ "$rc_val" != "0" ]; then
bash openebs-konvoy-e2e/utils/e2e-cr jobname:cvr-scaleup jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:$testResult
python3 openebs-konvoy-e2e/utils/result/result_update.py $job_id RUTT 3-functional "Verify the CVR scaled up successfully from one pool to another pool and check the volume status is healthy" $testResult $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

# Update the e2e cr once the job is completed
bash openebs-konvoy-e2e/utils/e2e-cr jobname:cvr-scaleup jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:$testResult

python3 openebs-konvoy-e2e/utils/result/result_update.py $job_id RUTT 3-functional "Verify the CVR scaled up successfully from one pool to another pool and check the volume status is healthy" $testResult $pipeline_id "$current_time" $commit_id $gittoken

if [ "$rc_val" != "0" ]; then
exit 1;
fi

}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5
else
  pod
fi