#!/bin/bash
set -x

#################
## ENVIRONMENT ##
#################

## https://github.com/openebs/litmus/blob/master/apps/fio/tests/data-integrity/test_vars.yml
run_id="cstor";test_name=$(${utils_path}/generate_test_name testcase=fio-data-integrity metadata=${run_id})

###################
## DEPENDENCIES  ##
###################

${utils_path}/setup_dependencies litmus-test

## Clone the litmus repo, navigate to litmus root 
git clone https://github.com/litmuschaos/litmus.git
cd litmus

############################
## LITMUS PRECONDITIONING ##
############################
: << EOF
  -------------------------------------------------------------------------------------------
 | specAttribute        | kind	   | jiva        	         | cStor-sparse  	    |
  -------------------------------------------------------------------------------------------
 | litmusJobLabel       | jobSpec  | fio-di-litmus               | fio-di-litmus-cstor      |
 | providerStorageClass | env 	   | openebs-standard            | openebs-cstor-sparse     |
 | appNamespace         | env	   | fio                         | fio-cstor                |
 | runID		| env(add) | 	-	         	 | cstor                    |
  -------------------------------------------------------------------------------------------
EOF

cp experiments/functional/fio/data-integrity/run_litmus_test.yml run_test.yml
sed -i -e 's/app: fio-di-litmus/app: fio-di-litmus-cstor/g' \
-e 's/value: openebs-standard/value: openebs-cstor-sparse/g' \
-e 's/value: fio/value: fio-cstor/g' run_test.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' run_test.yml

#################
## RUNNER MAIN ##
#################

echo "Running the litmus test.."
${utils_path}/litmus_job_runner label='app:fio-di-litmus-cstor' job=run_test.yml
${utils_path}/task_delimiter;

echo "Dumping state of cluster post job run"; echo ""
${utils_path}/dump_cluster_state;
${utils_path}/task_delimiter;

#################
## GET RESULT  ##
#################

## Check the test status & result from the litmus result custom resource
${utils_path}/get_litmus_result ${test_name}
