#!/bin/bash
set -ex
path=$(pwd)


cd $path/cluster

scp -r $path/cluster/konvoy_v0.6.0/* /usr/local/bin/

sudo konvoy down -y

sudo rm -rf *
sudo rm -rf /usr/local/bin/konvoy
sudo rm -rf /usr/local/bin/konvoy-preflight
sudo rm -rf /home/gitlab-runner/builds/sjPTxETt/0

pwd
