#!/bin/bash
set -x
path=$(pwd)


cd $path/cluster
sudo rm -rf /home/gitlab-runner/builds

sudo konvoy down -y

sudo rm -rf *
sudo rm -rf /usr/local/bin/konvoy
sudo rm -rf /usr/local/bin/konvoy-preflight
pwd
