#!/bin/bash
set -x

#################
## ENVIRONMENT ##
#################

run_id="localpv-device";test_name=$(${utils_path}/generate_test_name testcase=busybox-provision-app-busybox-device metadata=${run_id})

###################
## DEPENDENCIES  ##
###################
${utils_path}/setup_dependencies litmus-test

## Clone the litmus repo, navigate to litmus root 
git clone https://github.com/litmuschaos/litmus.git
cd litmus

############################
## LITMUS PRECONDITIONING ##
############################

: << EOF
  ------------------------------------------------------------------------------
 | specAttribute        | kind	   |  localpv                       	       |
  ------------------------------------------------------------------------------
 | litmusJobLabel       | jobSpec  |  busybox-provision-device               |
 | providerStorageClass | env 	   |  openebs-device                         |
 | appNamespace         | env	   |  app-busybox-device                     |
 | runID	            | env(add) |  localpv-device       	               |
 | appLabel             | env      |  busybox-sts-device                     |
  ------------------------------------------------------------------------------
EOF

cp apps/busybox/deployers/run_litmus_test.yml run_test.yml
sed -i -e 's/value: openebs-cstor-sparse/value: openebs-device/g' \
-e 's/app-busybox-ns/app-busybox-device/g' \
-e 's/app=busybox-sts/app=busybox-sts-device/g' \
-e 's/busybox-litmus/busybox-provision-device/g' \
-e 's/value: openebs.io\/target-affinity/value: openebs.io\/sts-target-affinity/g' run_test.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' run_test.yml

cat run_test.yml
#################
## RUNNER MAIN ##
#################

echo "Running the litmus test.."
${utils_path}/litmus_job_runner label='app:busybox-provision-device' job=run_test.yml
${utils_path}/task_delimiter;

echo "Dumping state of cluster post job run"; echo ""
${utils_path}/dump_cluster_state;
${utils_path}/task_delimiter;

#################
## GET RESULT  ##
#################

## Check the test status & result from the litmus result custom resource
${utils_path}/get_litmus_result ${test_name}
