#!/bin/bash
set -x

#################
## ENVIRONMENT ##
#################

run_id="localpv";test_name=$(${utils_path}/generate_test_name testcase=busybox-provision-app-busybox-ns metadata=${run_id})

###################
## DEPENDENCIES  ##
###################
${utils_path}/setup_dependencies litmus-test

## Clone the litmus repo, navigate to litmus root 
git clone https://github.com/litmuschaos/litmus.git
cd litmus

############################
## LITMUS PRECONDITIONING ##
############################

: << EOF
  ------------------------------------------------------------------------------
 | specAttribute        | kind	   |  localpv                       	       |
  ------------------------------------------------------------------------------
 | litmusJobLabel       | jobSpec  |  busybox-provision-app-busybox-ns-localpv |
 | providerStorageClass | env 	   |  openebs-hostpath                         |
 | appNamespace         | env	   |  app-busybox-ns                           |
 | runID		| env(add) |  localpv         	                       |
  ------------------------------------------------------------------------------
EOF

cp apps/busybox/deployers/run_litmus_test.yml run_test.yml
sed -i -e 's/value: openebs-cstor-sparse/value: openebs-hostpath/g' \
-e 's/value: openebs.io\/target-affinity/value: openebs.io\/sts-target-affinity/g' run_test.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' run_test.yml

#################
## RUNNER MAIN ##
#################

echo "Running the litmus test.."
${utils_path}/litmus_job_runner label='app:busybox-litmus' job=run_test.yml
${utils_path}/task_delimiter;

echo "Dumping state of cluster post job run"; echo ""
${utils_path}/dump_cluster_state;
${utils_path}/task_delimiter;

#################
## GET RESULT  ##
#################

## Check the test status & result from the litmus result custom resource
${utils_path}/get_litmus_result ${test_name}
