#!/bin/bash
set -x

#################
## ENVIRONMENT ##
#################

## https://github.com/openebs/litmus/blob/master/apps/cassandra/functional/scale_replicas/test_vars.yml 
test_name=$(${utils_path}/generate_test_name testcase=scale-app-replicas metadata="")

###################
## DEPENDENCIES  ##
###################

echo "Setting up test dependencies.."
 
${utils_path}/setup_dependencies litmus-test

## Clone the litmus repo, checkout the e2e branch, navigate to litmus root 

#git clone https://github.com/atulabhi/litmus.git
#cd litmus; git checkout v0.7-RC1

git clone https://github.com/litmuschaos/litmus.git
cd litmus

############################
## LITMUS PRECONDITIONING ##
############################

cp experiments/functional/scale_app_replica/run_litmus_test.yml run_test.yml

#################
## RUNNER MAIN ##
#################

echo "Running the litmus test.."

## Create the litmus job for cassandra app func test: scale-app-replicas

${utils_path}/litmus_job_runner label='app:cassandra-scaleup-litmus' job=run_test.yml
${utils_path}/task_delimiter;

echo "Dumping state of cluster post job run"; echo ""
${utils_path}/dump_cluster_state;
${utils_path}/task_delimiter;


#################
## GET RESULT  ##
#################

## Check the test status & result from the litmus result custom resource
${utils_path}/get_litmus_result ${test_name}
