#!/bin/bash
set -x

#################
## ENVIRONMENT ##
#################

## https://github.com/openebs/litmus/blob/master/apps/jenkins/upgrade/test_vars.yml 
run_id="cstor";test_name=$(${utils_path}/generate_test_name testcase=jenkins-upgrade-test metadata=${run_id})

###################
## DEPENDENCIES  ##
###################

${utils_path}/setup_dependencies litmus-test

## Clone the litmus repo, navigate to litmus root 
git clone https://github.com/litmuschaos/litmus.git
cd litmus

############################
## LITMUS PRECONDITIONING ##
############################
: << EOF
  ----------------------------------------------------------------------------------------
 | specAttribute        | kind     | jiva                   | cStor-sparse                 |
  ---------------------------------------------------------------------------------------- |
 | litmusJobLabel       | jobSpec  | upgrade-jenkins        | upgrade-jenkins-cstor        |
 | appNamespace         | env      | app-jenkins-ns         | jenkins-cstor                |
 | runID                | env(add) |    -                   | cstor 		           | 
  ----------------------------------------------------------------------------------------
EOF

cp apps/jenkins/upgrade/run_litmus_test.yml run_test.yml
sed -i -e 's/app: upgrade-jenkins/app: upgrade-jenkins-cstor/g' \
-e 's/value: app-jenkins-ns/value: jenkins-cstor/g' run_test.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' run_test.yml


#################
## RUNNER MAIN ##
#################

echo "Running the litmus test.."
${utils_path}/litmus_job_runner label='app:upgrade-jenkins-cstor' job=run_test.yml
${utils_path}/task_delimiter;

echo "Dumping state of cluster post job run"; echo ""
${utils_path}/dump_cluster_state;
${utils_path}/task_delimiter;

#################
## GET RESULT  ##
#################

## Check the test status & result from the litmus result custom resource
${utils_path}/get_litmus_result ${test_name}

