#!/bin/bash

pod() {
mkdir -p /root/.ssh
touch /root/.ssh/id_rsa
echo "$SSH_KEYS" > /root/.ssh/id_rsa
chmod 600 /root/.ssh/id_rsa
ssh -o StrictHostKeyChecking=no $user@$ip -p $port -i /root/.ssh/id_rsa 'cd e2e-konvoy && GOPATH="/home/d2iq/go"; PATH=$PATH:"/usr/local/go/bin:$GOPATH/bin"; /bin/bash /home/d2iq/e2e-konvoy/openebs-konvoy-e2e/stages/2-Infra-setup/BDD/cstor/negative/invalid-storage-pool-claim node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"'
}

node() {

job_id=$(echo $1) #Gitlab job id obtain from the gitlab env ($CI_JOB_ID).
pipeline_id=$(echo $2)  # Gitlab pipeline id obtained from gitlab env ($CI_PIPELINE_ID).
case_id=HC5P          # This need to be changed
commit_id=$(echo $3) #Gitlab commit id Obtained fron gilab env ($CI_COMMIT_SHA).

source ~/.profile

#github token to push the test result into github mayadata-io/e2e-konvoy repository.
#This token is set as an env in ~/.profile in the test cluster.

gittoken=$(echo "$github_token")

time="date"
current_time=$(eval $time)

#pooling over previous job to complete
bash openebs-konvoy-e2e/utils/pooling jobname:openebs-deploy
bash openebs-konvoy-e2e/utils/e2e-cr jobname:bdd-cstor-negative-invalid-storage-pool-claim jobphase:Running init_time:"$current_time" init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

cd /home/d2iq/go/src/github.com/openebs
git clone https://github.com/openebs/maya.git

# Running BDD test for jiva-clone
cd maya/tests/cstor/pool/negative && ginkgo -v -- -kubeconfig=$HOME/.kube/config --cstor-replicas=3 --cstor-maxpools=3

#Evaluating result based on the return count

if [ "$?" != "0" ];then
  echo "invalid-storage-pool-claim-test-failed"
  current_time=$(eval $time)
  cd /home/d2iq/e2e-konvoy
  bash openebs-konvoy-e2e/utils/e2e-cr jobname:bdd-cstor-negative-invalid-storage-pool-claim jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:Fail
  exit 1;
else
  echo "invalid-storage-pool-claim-test-Passed"
  current_time=$(eval $time)
  cd /home/d2iq/e2e-konvoy
  bash openebs-konvoy-e2e/utils/e2e-cr jobname:bdd-cstor-negative-invalid-storage-pool-claim jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:$testResult
fi
}

if [ "$1" == "node" ];then
  node $2 $3 $4
else
  pod
fi
