#!/bin/bash
set -x
path=$(pwd)
echo $path

cd $path
ls
cd config
aws configure set aws_access_key_id $ACCESS_KEY
aws configure set aws_secret_access_key $SECRET_KEY
cp konvoy-preflight konvoy /usr/local/bin/ 

sudo konvoy down -y