#!/bin/bash
set -x

#################
## ENVIRONMENT ##
#################

## https://github.com/openebs/litmus/blob/master/apps/percona/chaos/openebs_target_failure/test_vars.yml
run_id="";test_name=$(${utils_path}/generate_test_name testcase=application-pod-failure metadata=${run_id})

###################
## DEPENDENCIES  ##
###################

${utils_path}/setup_dependencies litmus-test

## Clone the litmus repo, navigate to litmus root 
git clone https://github.com/litmuschaos/litmus.git
cd litmus

############################
## LITMUS PRECONDITIONING ##
############################

## TODO: Add logic to replace job ENV (SC, PVC, LABEL, NS) based on run instance intent 
## TODO: Add logic to add ENV for run_instance_metadata/RunID

: << EOF
  -----------------------------------------------------------------------------------------------
 | specAttribute        | kind     | jiva                    | cStor-sparse                      |
  ----------------------------------------------------------------------------------------       |
 | litmusJobLabel       | jobSpec  | application-pod-failure | application-pod-failure-cassandra |
 | appNamespace         | env      | app-jenkins-ns          | app-cass-ns                       |
 | deploy_type          | env      | deployment              | statefulset                       |
 | app_label            | env(app) | app=jenkins-app         | app=cassandra                     |
  -----------------------------------------------------------------------------------------------
EOF

cp experiments/chaos/app_pod_failure/run_litmus_test.yml run_app_kill_test.yml

sed -i -e 's/name: application-pod-failure/name: application-pod-failure-cassandra/g' \
-e 's/value: app-jenkins-ns/value: app-cass-ns/g' \
-e 's/''app=jenkins-app''/''app=cassandra''/g' \
-e 's/value: deployment/value: statefulset/g' run_app_kill_test.yml

#################
## RUNNER MAIN ##
#################

echo "Running the litmus test.."
${utils_path}/litmus_job_runner label='name:application-pod-failure-cassandra' job=run_app_kill_test.yml
${utils_path}/task_delimiter;

echo "Dumping state of cluster post job run"; echo ""
${utils_path}/dump_cluster_state;
${utils_path}/task_delimiter;

#################
## GET RESULT  ##
#################

## Check the test status & result from the litmus result custom resource
${utils_path}/get_litmus_result ${test_name}


