#!/bin/bash
set -x

pod() {
echo $CI_JOB_ID
###clone e2e-openshift-repo
echo "cloning e2e-openshift repo*************"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p 1658 'git clone https://github.com/mayadata-io/e2e-konvoy.git'
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p 1658 'cd e2e-konvoy && git checkout konvoy-onprem && bash openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/6-cleanup/ISTV-cluster-cleanup/cluster-cleanup node '"'$CI_JOB_ID'"''
}

node() {
job_id=$(echo $1)

git clone https://github.com/mayadata-io/litmus.git
cd litmus

# Replace the VM IP In csv file
sed -i -e 's/10.12.22.10/10.34.1.162/g' \
-e 's/10.12.22.11/10.34.1.163/g' \
-e 's/10.12.22.12/10.34.1.164/g' \
-e 's/10.12.22.13/10.34.1.165/g' k8s/on-prem/openshift-installer/ip.csv

sed -i '/10.34.1.165/a \
10.34.1.166 \
10.34.1.167' k8s/on-prem/openshift-installer/ip.csv

#Replace the Vm names in csv file
sed -i -e 's/auto1/d2iq-master.mayalabs.io/g' \
-e 's/auto2/d2iq-node1.mayalabs.io/g' \
-e 's/auto3/d2iq-node2.mayalabs.io/g' \
-e 's/auto4/d2iq-node3.mayalabs.io/g' k8s/on-prem/openshift-installer/vm_name.csv

sed -i '/d2iq-node3.mayalabs.io/a \
d2iq-node4.mayalabs.io \
d2iq-node5.mayalabs.io' k8s/on-prem/openshift-installer/vm_name.csv

#Replace the snapshot name and exp ip in vars
sed -i -e 's/snapshot_name: "oc-cluster"/snapshot_name: "konvoy"/g' \
-e 's/esx_ip: "10.12.1.1"/esx_ip: "10.32.1.1"/g' k8s/on-prem/openshift-installer/vars.yml

ansible-playbook k8s/on-prem/openshift-installer/revert_cluster_state.yml -vv

#Removimg e2e openshift test repo
cd  && rm -rf e2e-konvoy && rm -rf infra
# cd /home/devuser/go/src/github.com/openebs && rm -rf maya
}

if [ "$1" == "node" ];then
  node $2
else
  pod
fi