#!/bin/bash


pod() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-konvoy && bash openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/ZDKG-local-pv-device/local-pv-device node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$RELEASE_TAG'"'
}

node() {
source ~/.profile
gittoken=$(echo "$github_token")

job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
releaseTag=$(echo $4)
case_id=ZDKG

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

bash openebs-konvoy-e2e/utils/e2e-cr jobname:local-pv-device jobphase:Waiting
bash openebs-konvoy-e2e/utils/e2e-cr jobname:local-pv-device jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag"

################
# LitmusBook 1 #
################

run_id="localpv";test_name=$(bash openebs-konvoy-e2e/utils/generate_test_name testcase=busybox-provision-busybox-device metadata=${run_id})
echo $test_name

cd litmus
cp apps/busybox/deployers/run_litmus_test.yml run_test_local_pv_device.yml

sed -i -e 's/app: busybox-litmus/app: busybox-local-pv-device/g' \
-e 's/app=busybox-sts/app=local-pv-device/g' \
-e 's/value: statefulset/value: deployment/g' \
-e 's/value: openebs-cstor-sparse/value: openebs-device/g' \
-e 's/value: openebs-busybox/value: openebs-busybox-device/g' \
-e 's/value: app-busybox-ns/value: busybox-device/g' run_test_local_pv_device.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' run_test_local_pv_device.yml

cat run_test_local_pv_device.yml

bash ../openebs-konvoy-e2e/utils/litmus_job_runner label='app:busybox-local-pv-device' job=run_test_local_pv_device.yml
cd ..
bash openebs-konvoy-e2e/utils/dump_cluster_state;
bash openebs-konvoy-e2e/utils/event_updater jobname:local-pv-device $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
python3 openebs-konvoy-e2e/utils/result/result_update.py $job_id ZDKG 3-functional "Deploy Application using Local device and checks the application status" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

run_id="localpv";test_name=$(bash openebs-konvoy-e2e/utils/generate_test_name testcase=busybox-deprovision-busybox-device metadata=${run_id})
echo $test_name

cd litmus
cp apps/busybox/deployers/run_litmus_test.yml run_test_deprovision_device.yml

sed -i -e 's/app: busybox-litmus/app: deprovision-busybox-local-pv-device/g' \
-e 's/app=busybox-sts/app=local-pv-device/g' \
-e 's/value: statefulset/value: deployment/g' \
-e 's/value: openebs-cstor-sparse/value: openebs-device/g' \
-e 's/value: openebs-busybox/value: openebs-busybox-device/g' \
-e 's/value: provision/value: deprovision/g' \
-e 's/value: app-busybox-ns/value: busybox-device/g' run_test_deprovision_device.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' run_test_deprovision_device.yml

cat run_test_deprovision_device.yml

bash ../openebs-konvoy-e2e/utils/litmus_job_runner label='app:deprovision-busybox-local-pv-device' job=run_test_deprovision_device.yml
cd ..
bash openebs-konvoy-e2e/utils/dump_cluster_state;
bash openebs-konvoy-e2e/utils/event_updater jobname:local-pv-device $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

rc_val=$(echo $?)
current_time=$(eval $time)

if [ "$rc_val" != "0" ]; then
bash openebs-konvoy-e2e/utils/e2e-cr jobname:local-pv-device jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Fail
python3 openebs-konvoy-e2e/utils/result/result_update.py $job_id ZDKG 3-functional "Deploy Application using Local device and checks the application status" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

bash openebs-konvoy-e2e/utils/e2e-cr jobname:local-pv-device jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Pass
python3 openebs-konvoy-e2e/utils/result/result_update.py $job_id ZDKG 3-functional "Deploy Application using Local device and checks the application status" Pass $pipeline_id "$current_time" $commit_id $gittoken

if [ "$rc_val" != "0" ]; then
exit 1;
fi

}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5
else
  pod
fi
