#!/bin/bash
set -x

pod() {	
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-konvoy && bash openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/ABZF-csi-volume-resize/csi-volume-resize node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"'
}

node() {
source ~/.profile
gittoken=$(echo "$github_token")

job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
case_id=ABZF

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

bash openebs-konvoy-e2e/utils/pooling jobname:deploy-busybox-csi
bash openebs-konvoy-e2e/utils/e2e-cr jobname:csi-volume-resize jobphase:Waiting init_time:"$current_time"
bash openebs-konvoy-e2e/utils/e2e-cr jobname:csi-volume-resize jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

run_id="csi";test_name=$(bash openebs-konvoy-e2e/utils/generate_test_name testcase=cstor-volume-resize metadata=${run_id})
echo $test_name

cd litmus
cp experiments/functional/cstor-volume-resize/run_litmus_test.yml run_cstor_volume_resize_test.yml

sed -i -e 's/value: percona-mysql-claim/value: openebs-busybox/g' \
-e 's/value: '\''name=percona'\''/value: '\''app=busybox-sts'\''/g' \
-e 's/app: litmus-cstor-vol-resize/app: litmus-cstor-vol-resize-csi/g' \
-e 's/value: app-percona-ns/value: busybox-csi/g' run_cstor_volume_resize_test.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' run_cstor_volume_resize_test.yml

cat run_cstor_volume_resize_test.yml

bash ../openebs-konvoy-e2e/utils/litmus_job_runner label='app:litmus-cstor-vol-resize-csi' job=run_cstor_volume_resize_test.yml
cd ..
bash openebs-konvoy-e2e/utils/dump_cluster_state;
bash openebs-konvoy-e2e/utils/event_updater jobname:csi-volume-resize $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
python3 openebs-konvoy-e2e/utils/result/result_update.py $job_id ABZF 4-chaos "Check if the volume size is changed" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

}

if [ "$1" == "node" ];then
  node $2 $3 $4
else
  pod
fi
