#!/bin/bash
set -x
pod() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-konvoy && bash openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/4-upgrade-openebs/upgrade-control-plane node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$RELEASE_TAG'"' '"'$FROM_VERSION'"' '"'$TO_VERSION'"' '"'$UPGRADE_IMAGE_TAG'"' '"'$NEW_NDM_TAG'"' '"'$DEPLOY_TYPE'"' '"'$HELM_REPO'"' '"'$HELM_BRANCH'"' '"'$UPGRADE_TO_CI'"'
}

node() {

time="date"
current_time=$(eval $time)
job_id=$(echo $1)
pipeline_id=$(echo $2)
releaseTag=$(echo $3)
from_version=$(echo $4)
to_version=$(echo $5)
upgrade_imageTag=$(echo $6)
new_ndmTag=$(echo $7)
deploy_type=$(echo $8)
helm_repo=$(echo $9)
helm_branch=$(echo ${10})
upgrade_to_ci=$(echo ${11})


source ~/.profile

present_dir=$(pwd)
echo $present_dir

bash openebs-konvoy-e2e/utils/e2e-cr jobname:upgrade-control-plane jobphase:Waiting
bash openebs-konvoy-e2e/utils/e2e-cr jobname:upgrade-control-plane jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" openebs_version:"$releaseTag"
bash openebs-konvoy-e2e/utils/e2e-cr jobname:upgrade-jiva jobphase:Waiting
bash openebs-konvoy-e2e/utils/e2e-cr jobname:upgrade-cstor jobphase:Waiting

test_name=$(bash openebs-konvoy-e2e/utils/generate_test_name testcase=openebs-upgrade metadata="")
echo $test_name

cd litmus
echo "Running the litmus test.."

cp providers/openebs/upgrade/run_litmus_test.yml upgrade_control_plane.yml

sed -i -e '/name: UPGRADE_CONTROL_PLANE/{n;s/.*/            value: "true"/}' \
-e '/name: FROM_VERSION/{n;s/.*/            value: '"'$from_version'"'/}' \
-e '/name: TO_VERSION/{n;s/.*/            value: '"'$to_version'"'/}' \
-e '/name: UPGRADE_IMAGE_TAG/{n;s/.*/            value: '"'$upgrade_imageTag'"'/}' \
-e '/name: NEW_NDM_TAG/{n;s/.*/            value: '"'$new_ndmTag'"'/}' \
-e '/name: UPGARDE_TO_CI/{n;s/.*/            value: '"'$upgrade_to_ci'"'/}' \
-e '/name: DEPLOY_TYPE/{n;s/.*/            value: '"'$deploy_type'"'/}' \
-e '/name: HELM_REPO/{n;s/.*/            value: '"'$helm_repo'"'/}' \
-e '/name: HELM_BRANCH/{n;s/.*/            value: '"'$helm_branch'"'/}' \
-e '/name: OPERATOR_NS/{n;s/.*/            value: openebs/}' upgrade_control_plane.yml

cat upgrade_control_plane.yml

bash ../openebs-konvoy-e2e/utils/litmus_job_runner label='app:openebs-upgrade' job=upgrade_control_plane.yml

echo "Dumping state of cluster post job run"; echo ""
bash ../openebs-konvoy-e2e/utils/dump_cluster_state;

cd ..
bash openebs-konvoy-e2e/utils/event_updater jobname:upgrade-control-plane $test_name jobid:"$job_id" pipelineid:"$pipeline_id"
#################
## GET RESULT  ##
#################
rc_val=$(echo $?)

## Check the test status & result from the litmus result custom resource
source ~/.profile
testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

current_time=$(eval $time)
bash openebs-konvoy-e2e/utils/e2e-cr jobname:upgrade-control-plane jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" openebs_version:"$releaseTag" test_result:$testResult

if [ "$rc_val" != "0" ]; then
exit 1;
fi

}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11} ${12}
else
  pod
fi