#!/bin/bash
set -x

#################
## ENVIRONMENT ##
#################

## https://github.com/openebs/litmus/blob/master/apps/percona/chaos/openebs_target_failure/test_vars.yml
run_id="cstor";test_name=$(${utils_path}/generate_test_name testcase=openebs-target-failure metadata=${run_id})

###################
## DEPENDENCIES  ##
###################

${utils_path}/setup_dependencies litmus-test

## Clone the litmus repo, navigate to litmus root 
git clone https://github.com/litmuschaos/litmus.git
cd litmus

############################
## LITMUS PRECONDITIONING ##
############################

: << EOF
  ----------------------------------------------------------------------------------------
 | specAttribute        | kind     | jiva                   | cStor-sparse                 |
  ---------------------------------------------------------------------------------------- |
 | litmusJobLabel       | jobSpec  | openebs-target-failure | openebs-target-failure-cstor |
 | appNamespace         | env      | app-percona-ns         | percona-cstor                |
 | runID                | env(add) |    -                   | cstor 		           | 
  ----------------------------------------------------------------------------------------
EOF

cp experiments/chaos/openebs_target_failure/run_litmus_test.yml run_test.yml
sed -i -e 's/name: openebs-target-failure/name: openebs-target-failure-cstor/g' \
-e 's/target-zrepl-kill/target-delete/g' \
-e 's/name: target-failure/name: target-failure-percona/g' \
-e 's/value: app-percona-ns/value: percona-cstor/g' run_test.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' run_test.yml

## Replace the value of DATA_PERSISTENCE with application name in litmus experiment. 
sed -i '/name: DATA_PERSISTENCE/{n;s/.*/            value: mysql/}' run_test.yml

## Insert the set of variables for percona data consistency util into configmap spec.
sed -i '/parameters.yml: |/a \
    dbuser: root\
    dbpassword: k8sDem0\
    dbname: tdb
' run_test.yml

cat run_test.yml

#################
## RUNNER MAIN ##
#################

echo "Running the litmus test.."
${utils_path}/litmus_job_runner label='name:openebs-target-failure-cstor' job=run_test.yml
${utils_path}/task_delimiter;

echo "Dumping state of cluster post job run"; echo ""
${utils_path}/dump_cluster_state;
${utils_path}/task_delimiter;

#################
## GET RESULT  ##
#################

## Check the test status & result from the litmus result custom resource
${utils_path}/get_litmus_result ${test_name}
