#!/bin/bash
set -x

pod(){
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-konvoy && bash openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/SBXW-jiva-csi-deploy-busybox/jiva-csi-deploy-busybox node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$RELEASE_TAG'"'
}

node() {
source ~/.profile
gittoken=$(echo "$github_token")
job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
releaseTag=$(echo $4)
case_id=SBXW

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

bash openebs-konvoy-e2e/utils/e2e-cr jobname:deploy-busybox-jiva-csi jobphase:Waiting
bash openebs-konvoy-e2e/utils/e2e-cr jobname:deploy-busybox-jiva-csi jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag"


################
# LitmusBook 1 #
################


echo "****Deploying busybox Application using Jiva CSI****"

test_name=$(bash openebs-konvoy-e2e/utils/generate_test_name testcase=jiva-csi-busybox metadata="")
echo $test_name

cd litmus
echo "Running the litmus test for busybox Deployment.."
cp experiments/functional/jiva-csi/jiva-csi-deploy-busybox/run_litmus_test.yml deploy_jiva_csi_busybox.yml

sed -i -e '/name: APP_LABEL/{n;s/.*/            value: jiva-csi-busybox/}' \
-e '/name: APP_NAMESPACE/{n;s/.*/            value: deploy-jiva-csi-busybox/}' \
-e '/name: PVC/{n;s/.*/            value: jiva-csi/}' deploy_jiva_csi_busybox.yml

cat deploy_jiva_csi_busybox.yml

bash ../openebs-konvoy-e2e/utils/litmus_job_runner label='app:jiva-csi-busybox' job=deploy_jiva_csi_busybox.yml
cd ..
bash openebs-konvoy-e2e/utils/dump_cluster_state;
bash openebs-konvoy-e2e/utils/event_updater jobname:deploy-busybox-jiva-csi $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
python3 openebs-konvoy-e2e/utils/result/result_update.py $job_id SBXW 3-functional "Provision application using Jiva CSI and verify the status" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# LitmusBook 2 #
################

echo "****Busybox liveness****"

run_id="jiva-csi";test_name=$(bash openebs-konvoy-e2e/utils/generate_test_name testcase=busybox-liveness metadata=${run_id})
echo $test_name

cd litmus
echo "Running the litmus test for busybox liveness..."
cp apps/busybox/liveness/run_litmus_test.yml liveness_jiva_csi_busybox.yml

sed -i -e 's/liveness: litmus-busybox-liveness/liveness: litmus-busybox-jiva-csi-liveness/g' \
-e 's/generateName: litmus-busybox-liveness-/generateName: litmus-busybox-jiva-csi-liveness-/g' \
-e 's/value: app-busybox-ns/value: deploy-jiva-csi-busybox/g' liveness_jiva_csi_busybox.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' liveness_jiva_csi_busybox.yml

cat liveness_jiva_csi_busybox.yml

bash ../openebs-konvoy-e2e/utils/litmus_job_runner label='liveness:litmus-busybox-jiva-csi-liveness' job=liveness_jiva_csi_busybox.yml
cd ..
bash openebs-konvoy-e2e/utils/dump_cluster_state;
bash openebs-konvoy-e2e/utils/event_updater jobname:deploy-busybox-jiva-csi $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"
rc_val=$(echo $?)
current_time=$(eval $time)

if [ "$rc_val" != "0" ]; then
bash openebs-konvoy-e2e/utils/e2e-cr jobname:deploy-busybox-jiva-csi jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Fail
python3 openebs-konvoy-e2e/utils/result/result_update.py $job_id SBXW 3-functional "Liveness on application and verify the status" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

bash openebs-konvoy-e2e/utils/e2e-cr jobname:deploy-busybox-jiva-csi jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Pass
python3 openebs-konvoy-e2e/utils/result/result_update.py $job_id SBXW 3-functional "Liveness on application and verify the status" Pass $pipeline_id "$current_time" $commit_id $gittoken

if [ "$rc_val" != "0" ]; then
exit 1;
fi

}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5
else
  pod
fi