#!/bin/bash
set -x

#################
## ENVIRONMENT ##
#################

## https://github.com/openebs/litmus/blob/master/apps/percona/workload/test_vars.yml
run_id="cstor";test_name=$(${utils_path}/generate_test_name testcase=mongodb-loadgen metadata=${run_id})

###################
## DEPENDENCIES  ##
###################

${utils_path}/setup_dependencies litmus-test

## Clone the litmus repo, navigate to litmus root 

git clone https://github.com/litmuschaos/litmus.git
cd litmus

############################
## LITMUS PRECONDITIONING ##
############################

: << EOF
  ------------------------------------------------------------------------------------
 | specAttribute        | kind     | jiva               | cStor-sparse                 |
  ------------------------------------------------------------------------------------
 | litmusJobLabel       | jobSpec  | mongodb-loadjob    | mongodb-loadjob-cstor        |
 | appNamespace         | env      | app-mongo-ns       | mongocstor                   |
 | runID                | env(add) |    -               | cstor                        |
  ------------------------------------------------------------------------------------
EOF

cp apps/mongodb/workload/run_litmus_test.yml run_test.yml

sed -i -e 's/loadgen: mongodb-loadjob/loadgen: mongodb-loadjob-cstor/g' \
-e 's/value: app-mongo-ns/value: mongocstor/g' run_test.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' run_test.yml

#################
## RUNNER MAIN ##
#################

echo "Running the litmus test.."
${utils_path}/litmus_job_runner label='loadgen:mongodb-loadjob-cstor' job=run_test.yml
${utils_path}/task_delimiter;

echo "Dumping state of cluster post job run"; echo ""
${utils_path}/dump_cluster_state;
${utils_path}/task_delimiter;

#################
## GET RESULT  ##
#################

## Check the test status & result from the litmus result custom resource
${utils_path}/get_litmus_result ${test_name}


