#!/bin/bash
set -x

pod() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-konvoy && bash openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/3-functional/UAFE-rwx-app-deploy/rwx-app-deploy node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$RELEASE_TAG'"'
}

node() {
job_id=$(echo $1)
pipeline_id=$(echo $2)
case_id=UAFE
time="date"
source ~/.profile
gittoken=$(echo "$github_token")
commit_id=$(echo $3)
releaseTag=$(echo $4)
current_time=$(eval $time)

bash openebs-konvoy-e2e/utils/e2e-cr jobname:app-deploy-rwx jobphase:Waiting
bash openebs-konvoy-e2e/utils/e2e-cr jobname:app-deploy-rwx jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag"

test_name=$(bash openebs-konvoy-e2e/utils/generate_test_name testcase=wordpress-deployment metadata="")
echo $test_name

cd litmus

echo "Running the litmus test.."
cp apps/wordpress/deployers/run_litmus_test.yml deploy_app.yml

# Replace the storage class name
sed -i -e 's/value: openebs-nfs/value: openebs-nfs4/g' deploy_app.yml

cat deploy_app.yml

bash ../openebs-konvoy-e2e/utils/litmus_job_runner label='app:wordpress-litmus' job=deploy_app.yml

echo "Dumping state of cluster post job run"; echo ""
cd ..
bash openebs-konvoy-e2e/utils/dump_cluster_state;

bash openebs-konvoy-e2e/utils/event_updater jobname:app-deploy-rwx $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
exit 1;
fi

#################
## GET RESULT  ##
#################

rc_val=$(echo $?)
test_case_id="UAFE"
source ~/.profile
gittoken=$(echo "$github_token")
testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

## Check the test status & result from the litmus result custom resource
current_time=$(eval $time)
bash openebs-konvoy-e2e/utils/e2e-cr jobname:app-deploy-rwx jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Pass

python3 openebs-konvoy-e2e/utils/result/result_update.py $job_id UAFE 3-functional "Deploy the application using nfs-provisioner accessmode as a readwritemany" $testResult $pipeline_id "$current_time" $commit_id $gittoken

if [ "$rc_val" != "0" ]; then
exit 1;
fi

}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5
else
  pod
fi