#!/bin/bash
set -ex
path=$(pwd)
echo $path
mkdir -p $path/config
ls
export AWS_ACCESS_KEY_ID=$ACCESS_KEY
export AWS_SECRET_ACCESS_KEY=$SECRET_KEY

git clone -b Openebs-base https://github.com/mayadata-io/e2e-konvoy.git
cd e2e-konvoy/openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/1-cluster-setup/P7Q4-cluster-setup
ls
sudo mv konvoy_v0.6.0_linux.tar.bz2 $path/config

tar -xf $path/config/konvoy_v0.6.0_linux.tar.bz2

sudo mv konvoy_v0.6.0 $path/config


sudo scp $path/config/konvoy_v0.6.0/* /usr/local/bin/
ls
cd $path/config
pwd
ls

sudo konvoy --version

sudo konvoy init

# Disabling default addons on cluster.yaml

#122-prometheusadapter
#128-velero
#120-prometheus
#110-kibana
#106-fluentbit
#104-elasticsearchexporter
#102-elasticsearch
#92-awsebscsiprovisioner
#29-control-plane

#94-awsebsprovisioner
#96-dashboard
#98-dex
#100-dex-k8s-authenticator
#102-elasticsearch
#112-kommander
#114-konvoy-ui
#118-opsportal
#120-prometheus
#124-traefik
#126-traefik-forward-auth


sed -i -e '128s/.*/      enabled: false/' \
-e '94s/.*/      enabled: false/' \
-e '96s/.*/      enabled: false/' \
-e '98s/.*/      enabled: false/' \
-e '100s/.*/      enabled: false/' \
-e '102s/.*/      enabled: false/' \
-e '112s/.*/      enabled: false/' \
-e '114s/.*/      enabled: false/' \
-e '118s/.*/      enabled: false/' \
-e '120s/.*/      enabled: false/' \
-e '124s/.*/      enabled: false/' \
-e '126s/.*/      enabled: false/' \
-e '122s/.*/      enabled: false/' \
-e '120s/.*/      enabled: false/' \
-e '110s/.*/      enabled: false/' \
-e '106s/.*/      enabled: false/' \
-e '104s/.*/      enabled: false/' \
-e '102s/.*/      enabled: false/' \
-e '92s/.*/      enabled: false/' \
-e '29s/.*/    count: 1/' cluster.yaml

# Bringing up cluster using konvoy up command

sudo konvoy up --cluster-name konvoypipeline -y

sudo konvoy apply kubeconfig

sudo mkdir ~/.kube

sudo scp $path/config/admin.conf ~/.kube/config

kubectl get nodes
kubectl get pods --all-namespaces
cd $path
