#!/bin/bash

pod() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-konvoy && bash openebs-konvoy-e2e/stages/2-Infra-setup/2IC06-storage-policies node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$RELEASE_TAG'"'
}

node() {

time="date"
current_time=$(eval $time)
job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
releaseTag=$(echo $4)
case_id=2IC06
source ~/.profile
gittoken=$(echo "$github_token")

present_dir=$(pwd)
echo $present_dir

#pooling over previous job to complete
echo "***********Applying openebs-storage-clas********"
bash openebs-konvoy-e2e/utils/pooling jobname:cstor-raidz2-pool
bash openebs-konvoy-e2e/utils/e2e-cr jobname:openebs-policies jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag"

test_name=$(bash openebs-konvoy-e2e/utils/generate_test_name testcase=cstor-storage-policies metadata="")
echo $test_name

cd e2e-tests

cp providers/cstor-storage-policies/run_e2e_test.yml cstor-sc.yaml

sed -i -e 's/imagePullPolicy: Always/imagePullPolicy: IfNotPresent/g' \
-e 's/cstor-sparse-pool/cstor-block-disk-pool-stripe/g' cstor-sc.yaml

cat cstor-sc.yaml

bash ../openebs-konvoy-e2e/utils/e2e_job_runner label='app:cstor-storage-policy' job=cstor-sc.yaml

echo "Dumping state of cluster post job run"; echo ""
bash ../openebs-konvoy-e2e/utils/dump_cluster_state;

cd ..
bash openebs-konvoy-e2e/utils/event_updater jobname:openebs-policies $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

#################
## GET RESULT  ##
#################

rc_val=$(echo $?)

## Check the test status & result from the e2e result custom resource
source ~/.profile
gittoken=$(echo "$github_token")
testResult=$(kubectl get e2eresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

current_time=$(eval $time)
bash openebs-konvoy-e2e/utils/e2e-cr jobname:openebs-policies jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:$testResult 

python3 openebs-konvoy-e2e/utils/result/result_update.py $job_id 2IC06 2-Infra-setup "Create K8s storage classes adhering the policies supported by OpenEBS" $testResult "$current_time" $gittoken

if [ "$rc_val" != "0" ]; then
exit 1;
fi

}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5
else
  pod
fi
