#!/bin/bash

mkdir -p /root/.ssh
touch /root/.ssh/id_rsa
echo "$SSH_KEYS" > /root/.ssh/id_rsa
chmod 600 /root/.ssh/id_rsa

ssh -o StrictHostKeyChecking=no $user@$ip -p $port -i /root/.ssh/id_rsa 'cd e2e-konvoy && bash openebs-konvoy-e2e/stages/2-Infra-setup/2IC02-create-striped-pool node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$RELEASE_TAG'"'

}

node() {

job_id=$(echo $1)
pipeline_id=$(echo $2)
case_id=2IC02
commit_id=$(echo $3)
releaseTag=$(echo $4)
source ~/.profile
gittoken=$(echo "$github_token")

time="date"
current_time=$(eval $time)

#pooling over previous job to complete
echo "*******Creating cstor-pool**************"
bash openebs-konvoy-e2e/utils/pooling jobname:cstor-integration-test
bash openebs-konvoy-e2e/utils/e2e-cr jobname:cstor-striped-pool jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag"

run_id="striped";test_name=$(bash openebs-konvoy-e2e/utils/generate_test_name testcase=cstor-block-device-pool-provision metadata=${run_id})
echo $test_name
cd e2e-tests

cp providers/cstor/cstor-block-device-pool/run_e2e_test.yml create_striped_pool.yml

#################
## RUNNER MAIN ##
#################
echo "Running the e2e test.."

: << EOF
  ---------------------------------------------------------------------------------------------------------------------------------------------   
 | specAttribute     | kind   |         default value                           | test specific value                                           |
  ---------------------------------------------------------------------------------------------------------------------------------------------
 | e2e job label  | label  | app: cstor-block-device-pool-provision          | app: cstor-striped-pool-provision                            |
 | e2e Job name   | name   | generateName: cstor-block-device-pool-provision | generateName: cstor-block-device-striped-pool-provision      |
 | ImagePullPolicy   | value  | Always                                          | IfNotPresent                                                 |
 | Pool name         | name   | cstor-block-disk-pool                           | cstor-block-disk-pool-stripe                                 |
 ---------------------------------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/app: cstor-block-device-pool-provision/app: cstor-striped-pool-provision/g' \
-e 's/generateName: cstor-block-device-pool-provision/generateName: cstor-block-device-striped-pool-provision/g' \
-e 's/imagePullPolicy: Always/imagePullPolicy: IfNotPresent/g' \
-e 's/value: cstor-block-disk-pool/value: cstor-block-disk-pool-stripe/g' create_striped_pool.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' create_striped_pool.yml

cat create_striped_pool.yml

bash ../openebs-konvoy-e2e/utils/e2e_job_runner label='app:cstor-striped-pool-provision' job=create_striped_pool.yml
bash ../openebs-konvoy-e2e/utils/dump_cluster_state;
cd ..
bash openebs-konvoy-e2e/utils/event_updater jobname:cstor-striped-pool $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

#################
## GET RESULT  ##
#################
rc_val=$(echo $?)

## Check the test status & result from the e2e result custom resource
source ~/.profile
gittoken=$(echo "$github_token")

testResult=$(kubectl get e2eresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

current_time=$(eval $time)
bash openebs-konvoy-e2e/utils/e2e-cr jobname:cstor-striped-pool jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:$testResult

python3 openebs-konvoy-e2e/utils/result/result_update.py $job_id 2IC02 2-Infra-setup "Create cStor based Striped storage pool on disks and corresponding storage class" $testResult "$current_time" $gittoken

if [ "$rc_val" != "0" ]; then
exit 1;
fi
}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5
else
  pod
fi
