#!/bin/bash

pod() {

sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-konvoy && bash openebs-konvoy-e2e/stages/2-Infra-setup/2IC07-create-nfs-provisioner node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$RELEASE_TAG'"'

}

node() {

job_id=$(echo $1)
pipeline_id=$(echo $2)
case_id=2IC07
commit_id=$(echo $3)
releaseTag=$(echo $4)
source ~/.profile
gittoken=$(echo "$github_token")

time="date"
current_time=$(eval $time)

#pooling over previous job to complete
bash openebs-konvoy-e2e/utils/pooling jobname:openebs-policies
bash openebs-konvoy-e2e/utils/e2e-cr jobname:nfsv4-provision jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag"

test_name=$(bash openebs-konvoy-e2e/utils/generate_test_name testcase=nfs-provision metadata="")
echo $test_name
cd e2e-tests

# copy the content of deployer run_litmus_test.yml into a different file to update the test specific parameters.
cp providers/nfs-provisioner/run_litmus_test.yml nfsv4-provision.yml

sed -i -e 's/imagePullPolicy: Always/imagePullPolicy: IfNotPresent/g' \
-e 's/value: app-nfs-ns/value: app-nfsv4-ns/g' \
-e 's/value: openebs-nfs/value: openebs-nfs4/g' nfsv4-provision.yml

#################
## RUNNER MAIN ##
#################

cat nfsv4-provision.yml

bash ../openebs-konvoy-e2e/utils/litmus_job_runner label='app:nfs-litmus' job=nfsv4-provision.yml
bash ../openebs-konvoy-e2e/utils/dump_cluster_state;
cd ..
bash openebs-konvoy-e2e/utils/event_updater jobname:nfsv4-provision $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

#################
## GET RESULT  ##
#################
rc_val=$(echo $?)

## Check the test status & result from the litmus result custom resource
source ~/.profile
gittoken=$(echo "$github_token")
testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

current_time=$(eval $time)
bash openebs-konvoy-e2e/utils/e2e-cr jobname:nfsv4-provision jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:$testResult

python3 openebs-konvoy-e2e/utils/result/result_update.py $job_id 2IC07 2-Infra-setup "Create NFS provisioner vers 4.1 and corresponding storage class" $testResult "$current_time" $gittoken

if [ "$rc_val" != "0" ]; then
exit 1;
fi
}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5
else
  pod
fi
