#!/bin/bash
set -x

pod(){
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-konvoy && bash openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-cstor-verify-data-persistence node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$RELEASE_TAG'"'
}

node(){
source ~/.profile
job_id=$(echo $1)
pipeline_id=$(echo $2)
releaseTag=$(echo $3)
time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

bash openebs-konvoy-e2e/utils/e2e-cr jobname:bb-verify-data-persistence jobphase:Waiting
bash openebs-konvoy-e2e/utils/e2e-cr jobname:bb-verify-data-persistence jobphase:Running init_time:"$current_time" job_id:"$job_id" pipeline_id:"$pipeline_id" openebs_version:"$releaseTag"

##############################
# Verifying Data-persistence #
##############################

run_id="bb-sts-cstor-verify";test_name=$(bash openebs-konvoy-e2e/utils/generate_test_name testcase=data-persistence-check metadata=${run_id})
echo $test_name

cd litmus
echo "Running Litmus Book for verifying data-persistence against busybox application."
cp experiments/functional/data-persistence/run_litmus_test.yml run_verify_data_persistence.yml

sed -i -e 's/generateName: data-persistence-litmus-/generateName: data-persistence-busybox-cstor-/g' \
-e 's/name: litmus-data-persistence/name: data-persistence-busybox-cstor-verify/g' \
-e '/name: APP_NAMESPACE/{n;s/.*/            value: bb-cstor-statefulset/}' \
-e '/name: APP_LABEL/{n;s/.*/            value: '\''app=busybox-sts'\''/}' \
-e '/name: STATUS/{n;s/.*/           value: VERIFY/}' \
-e '/name: DATA_PERSISTENCE/{n;s/.*/            value: busybox/}' run_verify_data_persistence.yml

## Insert the set of variables for busybox data consistency util into configmap spec.
sed -i '/parameters.yml: |/a \
    blocksize: 4k \
    blockcount: 1024 \
    testfile: busybox_deployment_cstor
' run_verify_data_persistence.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' run_verify_data_persistence.yml

cat run_verify_data_persistence.yml

bash ../openebs-konvoy-e2e/utils/litmus_job_runner label='name:data-persistence-busybox-cstor-verify' job=run_verify_data_persistence.yml
cd ..

bash openebs-konvoy-e2e/utils/dump_cluster_state;
bash openebs-konvoy-e2e/utils/event_updater jobname:bb-verify-data-persistence $test_name jobid:"$job_id" pipeline_id:"$pipeline_id"

if [ "$?" != "0" ]; then
exit 1;
fi

##############################################
# Delete Files after Verify Data-Persistence #
##############################################

run_id="bb-sts-cstor-delete";test_name=$(bash openebs-konvoy-e2e/utils/generate_test_name testcase=data-persistence-check metadata=${run_id})
echo $test_name

cd litmus
cp experiments/functional/data-persistence/run_litmus_test.yml run_bb_delete_data_files.yml

sed -i -e 's/generateName: data-persistence-litmus-/generateName: data-persistence-busybox-cstor-/g' \
-e 's/name: litmus-data-persistence/name: data-persistence-busybox-cstor-delete/g' \
-e '/name: APP_NAMESPACE/{n;s/.*/            value: bb-cstor-deployment/}' \
-e '/name: APP_LABEL/{n;s/.*/            value: '\''app=busybox-sts'\''/}' \
-e '/name: STATUS/{n;s/.*/           value: DELETE/}' \
-e '/name: DATA_PERSISTENCE/{n;s/.*/            value: busybox/}' run_bb_delete_data_files.yml

## Insert the set of variables for busybox data consistency util into configmap spec.
sed -i '/parameters.yml: |/a \
    blocksize: 4k \
    blockcount: 1024 \
    testfile: busybox_deployment_cstor
' run_bb_delete_data_files.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' run_bb_delete_data_files.yml

cat run_bb_delete_data_files.yml

bash ../openebs-konvoy-e2e/utils/litmus_job_runner label='name:data-persistence-busybox-cstor-delete' job=run_bb_delete_data_files.yml
cd ..

bash openebs-konvoy-e2e/utils/dump_cluster_state;
bash openebs-konvoy-e2e/utils/event_updater jobname:bb-verify-data-persistence $test_name jobid:"$job_id" pipeline_id:"$pipeline_id"

rc_val=$(echo $?)
current_time=$(eval $time)

if [ "$rc_val" != "0" ]; then
bash openebs-konvoy-e2e/utils/e2e-cr jobname:bb-verify-data-persistence jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" openebs_version:"$releaseTag" test_result:Fail
exit 1;
fi

bash openebs-konvoy-e2e/utils/e2e-cr jobname:bb-verify-data-persistence jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" openebs_version:"$releaseTag" test_result:Pass

}

if [ "$1" == "node" ];then
  node $2 $3 $4
else
  pod
fi