#!/bin/bash
set -x

pod(){
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-konvoy && bash openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/bb-deployment-controller-nw-delay node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$RELEASE_TAG'"'
}

node(){
source ~/.profile
job_id=$(echo $1)
pipeline_id=$(echo $2)
releaseTag=$(echo $3)
time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

bash openebs-konvoy-e2e/utils/pooling jobname:bb-controller-kill
bash openebs-konvoy-e2e/utils/e2e-cr jobname:bb-controller-nw-delay jobphase:Running init_time:"$current_time" job_id:"$job_id" pipeline_id:"$pipeline_id" openebs_version:"$releaseTag"

##############################
# Verifying Data-persistence #
##############################

run_id="bb-jiva-verify";test_name=$(bash openebs-konvoy-e2e/utils/generate_test_name testcase=data-persistence-check metadata=${run_id})
echo $test_name

cd litmus
echo "Running Litmus Book for verifying data-persistence against busybox application."
cp experiments/functional/data-persistence/run_litmus_test.yml bb_deployment_jiva_verify_data_persistence.yml

sed -i -e 's/generateName: data-persistence-litmus-/generateName: data-persistence-busybox-jiva-/g' \
-e 's/name: litmus-data-persistence/name: data-persistence-busybox-jiva-nw-delay-verify/g' \
-e '/name: APP_NAMESPACE/{n;s/.*/            value: bb-jiva-deployment/}' \
-e '/name: APP_LABEL/{n;s/.*/            value: '\''app=busybox-sts'\''/}' \
-e '/name: STATUS/{n;s/.*/            value: VERIFY/}' \
-e '/name: DATA_PERSISTENCE/{n;s/.*/            value: busybox/}' bb_deployment_jiva_verify_data_persistence.yml

## Insert the set of variables for busybox data consistency util into configmap spec.
sed -i '/parameters.yml: |/a \
    blocksize: 4k \
    blockcount: 1024 \
    testfile: busybox_deployment_jiva
' bb_deployment_jiva_verify_data_persistence.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' bb_deployment_jiva_verify_data_persistence.yml

cat bb_deployment_jiva_verify_data_persistence.yml

bash ../openebs-konvoy-e2e/utils/litmus_job_runner label='name:data-persistence-busybox-jiva-nw-delay-verify' job=bb_deployment_jiva_verify_data_persistence.yml
cd ..

bash openebs-konvoy-e2e/utils/dump_cluster_state;
bash openebs-konvoy-e2e/utils/event_updater jobname:bb-controller-nw-delay $test_name jobid:"$job_id" pipeline_id:"$pipeline_id"

if [ "$?" != "0" ]; then
exit 1;
fi

##############################################
# Delete Files after Verify Data-Persistence #
##############################################

run_id="bb-jiva-delete";test_name=$(bash openebs-konvoy-e2e/utils/generate_test_name testcase=data-persistence-check metadata=${run_id})
echo $test_name

cd litmus
cp experiments/functional/data-persistence/run_litmus_test.yml bb_deployment_jiva_delete_file.yml

sed -i -e 's/generateName: data-persistence-litmus-/generateName: data-persistence-busybox-jiva-/g' \
-e 's/name: litmus-data-persistence/name: data-persistence-busybox-jiva-nw-delay-delete/g' \
-e '/name: APP_NAMESPACE/{n;s/.*/            value: bb-jiva-deployment/}' \
-e '/name: APP_LABEL/{n;s/.*/            value: '\''app=busybox-sts'\''/}' \
-e '/name: STATUS/{n;s/.*/            value: DELETE/}' \
-e '/name: DATA_PERSISTENCE/{n;s/.*/            value: busybox/}' bb_deployment_jiva_delete_file.yml

## Insert the set of variables for busybox data consistency util into configmap spec.
sed -i '/parameters.yml: |/a \
    blocksize: 4k \
    blockcount: 1024 \
    testfile: busybox_deployment_jiva
' bb_deployment_jiva_delete_file.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' bb_deployment_jiva_delete_file.yml

cat bb_deployment_jiva_delete_file.yml

bash ../openebs-konvoy-e2e/utils/litmus_job_runner label='name:data-persistence-busybox-jiva-nw-delay-delete' job=bb_deployment_jiva_delete_file.yml
cd ..

bash openebs-konvoy-e2e/utils/dump_cluster_state;
bash openebs-konvoy-e2e/utils/event_updater jobname:bb-controller-nw-delay $test_name jobid:"$job_id" pipeline_id:"$pipeline_id"

if [ "$?" != "0" ]; then
exit 1;
fi

##########################################
## Performing controller-network-delay test ##
##########################################

run_id="bb-jiva";test_name=$(bash openebs-konvoy-e2e/utils/generate_test_name testcase=openebs-target-network-delay metadata=${run_id})
echo $test_name

cd litmus
cp experiments/chaos/openebs_controller_network_delay/run_litmus_test.yml run_bb_controller_nw_delay.yml

sed -i -e 's/value: percona-mysql-claim/value: openebs-busybox/g' \
-e 's/openebs-controller-network-delay/bb-deployment-controller-nw-delay/g' \
-e 's/value: '\''name=percona'\''/value: '\''app=busybox-sts'\''/g' \
-e 's/value: docker/value: containerd/g' \
-e 's/value: app-percona-ns/value: bb-jiva-deployment/g' run_bb_controller_nw_delay.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' run_bb_controller_nw_delay.yml
            
## Replace the value of DATA_PERSISTENCE with application name in litmus experiment.
sed -i '/name: DATA_PERSISTENCE/{n;s/.*/            value: busybox/}' run_bb_controller_nw_delay.yml

## Insert the set of variables for busybox data consistency util into configmap spec.
sed -i '/parameters.yml: |/a \
    blocksize: 4k \
    blockcount: 1024 \
    testfile: controllernwdelaytest
' run_bb_controller_nw_delay.yml

cat run_bb_controller_nw_delay.yml

bash ../openebs-konvoy-e2e/utils/litmus_job_runner label='name:bb-deployment-controller-nw-delay' job=run_bb_controller_nw_delay.yml
cd..

bash openebs-konvoy-e2e/utils/dump_cluster_state;
bash openebs-konvoy-e2e/utils/event_updater jobname:bb-controller-nw-delay $test_name jobid:"$job_id" pipeline_id:"$pipeline_id"

rc_val=$(echo $?)
current_time=$(eval $time)

if [ "$rc_val" != "0" ]; then
bash openebs-konvoy-e2e/utils/e2e-cr jobname:bb-controller-nw-delay jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" openebs_version:"$releaseTag" test_result:Fail
exit 1;
fi

bash openebs-konvoy-e2e/utils/e2e-cr jobname:bb-controller-nw-delay jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" openebs_version:"$releaseTag" test_result:Pass

if [ "$1" == "node" ];then
  node $2 $3 $4
else
  pod
fi
}
