#!/bin/bash
set -x

pod(){
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-konvoy && bash openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/percona-deployment-device node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$RELEASE_TAG'"'
}

node(){
source ~/.profile
job_id=$(echo $1)
pipeline_id=$(echo $2)
releaseTag=$(echo $3)
time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

bash openebs-konvoy-e2e/utils/e2e-cr jobname:percona-device jobphase:Waiting
bash openebs-konvoy-e2e/utils/e2e-cr jobname:percona-device jobphase:Running init_time:"$current_time" job_id:"$job_id" pipeline_id:"$pipeline_id" openebs_version:"$releaseTag"

## Deploying percona application...

run_id="device";test_name=$(bash openebs-konvoy-e2e/utils/generate_test_name testcase=percona-deployment metadata=${run_id})
echo $test_name

cd litmus
echo "Running the litmus test for percona Deployment..."
cp apps/percona/deployers/run_litmus_test.yml percona_device.yml

sed -i -e 's/app: percona-deployment/app: percona-deploy-device/g' \
-e 's/value: openebs-standard/value: openebs-device/g' \
-e 's/value: enable/value: disable/g' \
-e 's/value: app-percona-ns/value: percona-device-ns/g' percona_device.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' percona_device.yml

cat percona_device.yml

bash ../openebs-konvoy-e2e/utils/litmus_job_runner label='app:percona-deploy-device' job=percona_device.yml
cd ..

bash openebs-konvoy-e2e/utils/dump_cluster_state;
bash openebs-konvoy-e2e/utils/event_updater jobname:percona-device $test_name jobid:"$job_id" pipeline_id:"$pipeline_id"

if [ "$?" != "0" ]; then
exit 1;
fi

##DATA-PERSISTENCE-load

run_id="percona-device-load";test_name=$(bash openebs-konvoy-e2e/utils/generate_test_name testcase=data-persistence-check metadata=${run_id})
echo $test_name

cd litmus
echo "Running the litmus experiment to check data-persistence for percona Application..."
cp experiments/functional/data-persistence/run_litmus_test.yml percona_device_load.yml

sed -i -e 's/generateName: data-persistence-litmus-/generateName: data-persistence-percona-device-/g' \
-e 's/name: data-persistence/name: percona-device-cm/g' \
-e 's/name: litmus-data-persistence/name: percona-device-load/g' \
-e '/name: APP_NAMESPACE/{n;s/.*/            value: percona-device-ns/}' \
-e '/name: APP_LABEL/{n;s/.*/            value: '\''name=percona'\''/}' \
-e '/name: STATUS/{n;s/.*/            value: LOAD/}' \
-e '/name: DATA_PERSISTENCE/{n;s/.*/            value: mysql/}' percona_device_load.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' percona_device_load.yml

## Insert the set of variables for percona data consistency util into configmap spec.
sed -i '/parameters.yml: |/a \
    dbuser: root \
    dbpassword: k8sDem0 \
    dbname: db_percona_device
' percona_device_load.yml

cat percona_device_load.yml

bash ../openebs-konvoy-e2e/utils/litmus_job_runner label='name:percona-device-load' job=percona_device_load.yml
cd ..

bash openebs-konvoy-e2e/utils/dump_cluster_state;
bash openebs-konvoy-e2e/utils/event_updater jobname:percona-device $test_name jobid:"$job_id" pipeline_id:"$pipeline_id"

if [ "$?" != "0" ]; then
exit 1;
fi

##DATA-PERSISTENCE-verify

run_id="percona-device-verify";test_name=$(bash openebs-konvoy-e2e/utils/generate_test_name testcase=data-persistence-check metadata=${run_id})
echo $test_name

cd litmus
echo "Running the litmus experiment to check data-persistence for percona Application..."
cp experiments/functional/data-persistence/run_litmus_test.yml percona_device_verify.yml

sed -i -e 's/generateName: data-persistence-litmus-/generateName: data-persistence-percona-device-/g' \
-e 's/name: data-persistence/name: percona-device-cm/g' \
-e 's/name: litmus-data-persistence/name: percona-device-verify/g' \
-e '/name: APP_NAMESPACE/{n;s/.*/            value: percona-device-ns/}' \
-e '/name: APP_LABEL/{n;s/.*/            value: '\''name=percona'\''/}' \
-e '/name: STATUS/{n;s/.*/            value: VERIFY/}' \
-e '/name: DATA_PERSISTENCE/{n;s/.*/            value: mysql/}' percona_device_verify.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' percona_device_verify.yml

## Insert the set of variables for percona data consistency util into configmap spec.
sed -i '/parameters.yml: |/a \
    dbuser: root \
    dbpassword: k8sDem0 \
    dbname: db_percona_device
' percona_device_verify.yml

cat percona_device_verify.yml

bash ../openebs-konvoy-e2e/utils/litmus_job_runner label='name:percona-device-verify' job=percona_device_verify.yml
cd ..

bash openebs-konvoy-e2e/utils/dump_cluster_state;
bash openebs-konvoy-e2e/utils/event_updater jobname:percona-device $test_name jobid:"$job_id" pipeline_id:"$pipeline_id"

if [ "$?" != "0" ]; then
exit 1;
fi

##DATA-PERSISTENCE-delete

run_id="percona-device-delete";test_name=$(bash openebs-konvoy-e2e/utils/generate_test_name testcase=data-persistence-check metadata=${run_id})
echo $test_name

cd litmus
echo "Running the litmus experiment to check data-persistence for percona Application..."
cp experiments/functional/data-persistence/run_litmus_test.yml percona_device_delete.yml

sed -i -e 's/generateName: data-persistence-litmus-/generateName: data-persistence-percona-device-/g' \
-e 's/name: data-persistence/name: percona-device-cm/g' \
-e 's/name: litmus-data-persistence/name: percona-device-delete/g' \
-e '/name: APP_NAMESPACE/{n;s/.*/            value: percona-device-ns/}' \
-e '/name: APP_LABEL/{n;s/.*/            value: '\''name=percona'\''/}' \
-e '/name: STATUS/{n;s/.*/            value: DELETE/}' \
-e '/name: DATA_PERSISTENCE/{n;s/.*/            value: mysql/}' percona_device_delete.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' percona_device_delete.yml

## Insert the set of variables for percona data consistency util into configmap spec.
sed -i '/parameters.yml: |/a \
    dbuser: root \
    dbpassword: k8sDem0 \
    dbname: db_percona_device
' percona_device_delete.yml

cat percona_device_delete.yml

bash ../openebs-konvoy-e2e/utils/litmus_job_runner label='name:percona-device-delete' job=percona_device_delete.yml
cd ..

bash openebs-konvoy-e2e/utils/dump_cluster_state;
bash openebs-konvoy-e2e/utils/event_updater jobname:percona-device $test_name jobid:"$job_id" pipeline_id:"$pipeline_id"

rc_val=$(echo $?)
current_time=$(eval $time)

if [ "$rc_val" != "0" ]; then
bash openebs-konvoy-e2e/utils/e2e-cr jobname:percona-device jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" openebs_version:"$releaseTag" test_result:Fail
exit 1;
fi

bash openebs-konvoy-e2e/utils/e2e-cr jobname:percona-device jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" openebs_version:"$releaseTag" test_result:Pass

}

if [ "$1" == "node" ];then
  node $2 $3 $4
else
  pod
fi
