#!/bin/bash
set -x

pod(){
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-konvoy && bash openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/percona-controller-nw-delay node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$RELEASE_TAG'"'
}

node(){
source ~/.profile
job_id=$(echo $1)
pipeline_id=$(echo $2)
releaseTag=$(echo $3)
time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

bash openebs-konvoy-e2e/utils/e2e-cr jobname:percona-controller-nw-delay jobphase:Waiting
bash openebs-konvoy-e2e/utils/e2e-cr jobname:percona-controller-nw-delay jobphase:Running init_time:"$current_time" job_id:"$job_id" pipeline_id:"$pipeline_id" openebs_version:"$releaseTag"

##############################
# Verifying Data-persistence #
##############################

run_id="percona-jiva-verify";test_name=$(bash openebs-konvoy-e2e/utils/generate_test_name testcase=data-persistence-check metadata=${run_id})
echo $test_name

cd litmus
echo "Running Litmus Book for verifying data-persistence against percona application."
cp experiments/functional/data-persistence/run_litmus_test.yml percona_jiva_verify_data_persistence.yml

sed -i -e 's/generateName: data-persistence-litmus-/generateName: data-persistence-percona-jiva-/g' \
-e 's/name: data-persistence/name: percona-jiva-configmap/g' \
-e 's/name: litmus-data-persistence/name: data-persistence-percona-jiva-verify/g' \
-e '/name: APP_NAMESPACE/{n;s/.*/            value: percona-jiva/}' \
-e '/name: APP_LABEL/{n;s/.*/            value: '\''name=percona'\''/}' \
-e '/name: STATUS/{n;s/.*/            value: VERIFY/}' \
-e '/name: DATA_PERSISTENCE/{n;s/.*/            value: mysql/}' percona_jiva_verify_data_persistence.yml

## Insert the set of variables for percona data consistency util into configmap spec.
sed -i '/parameters.yml: |/a \
    dbuser: root \
    dbpassword: k8sDem0 \
    dbname: tdb
' percona_jiva_verify_data_persistence.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' percona_jiva_verify_data_persistence.yml

cat percona_jiva_verify_data_persistence.yml

bash ../openebs-konvoy-e2e/utils/litmus_job_runner label='name:data-persistence-percona-jiva-verify' job=percona_jiva_verify_data_persistence.yml
cd ..

bash openebs-konvoy-e2e/utils/dump_cluster_state;
bash openebs-konvoy-e2e/utils/event_updater jobname:percona-controller-nw-delay $test_name jobid:"$job_id" pipeline_id:"$pipeline_id"

if [ "$?" != "0" ]; then
exit 1;
fi

##############################################
# Delete Files after Verify Data-Persistence #
##############################################

run_id="percona-jiva-delete";test_name=$(bash openebs-konvoy-e2e/utils/generate_test_name testcase=data-persistence-check metadata=${run_id})
echo $test_name

cd litmus
cp experiments/functional/data-persistence/run_litmus_test.yml percona_jiva_delete_data_files.yml

sed -i -e 's/generateName: data-persistence-litmus-/generateName: data-persistence-percona-jiva-/g' \
-e 's/name: data-persistence/name: percona-jiva-configmap/g' \
-e 's/name: data-persistence-litmus/name: data-persistence-percona-jiva-delete/g' \
-e '/name: APP_NAMESPACE/{n;s/.*/            value: percona-jiva/}' \
-e '/name: APP_LABEL/{n;s/.*/            value: '\''name=percona'\''/}' \
-e '/name: STATUS/{n;s/.*/            value: DELETE/}' \
-e '/name: DATA_PERSISTENCE/{n;s/.*/            value: mysql/}' percona_jiva_delete_data_files.yml

## Insert the set of variables for percona data consistency util into configmap spec.
sed -i '/parameters.yml: |/a \
    dbuser: root \
    dbpassword: k8sDem0 \
    dbname: tdb
' percona_jiva_delete_data_files.yml

cat percona_jiva_delete_data_files.yml

bash ../openebs-konvoy-e2e/utils/litmus_job_runner label='name:data-persistence-percona-jiva-delete' job=percona_jiva_delete_data_files.yml
cd ..

bash openebs-konvoy-e2e/utils/dump_cluster_state;
bash openebs-konvoy-e2e/utils/event_updater jobname:percona-controller-nw-delay $test_name jobid:"$job_id" pipeline_id:"$pipeline_id"

if [ "$?" != "0" ]; then
exit 1;
fi
##########################################
## Performing controller-network-delay test ##
##########################################

run_id="percona-jiva";test_name=$(bash openebs-konvoy-e2e/utils/generate_test_name testcase=openebs-target-network-delay metadata=${run_id})
echo $test_name

cd litmus
cp experiments/chaos/openebs_controller_network_delay/run_litmus_test.yml run_percona_controller_nw_delay.yml

sed -i -e 's/openebs-controller-network-delay/percona-controller-nw-delay/g' \
-e 's/name: target-network-delay/name: controller-network-delay-configmap/g' \
-e 's/value: docker/value: containerd/g' \
-e 's/value: app-percona-ns/value: percona-jiva/g' run_percona_controller_nw_delay.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' run_percona_controller_nw_delay.yml   

## Replace the value of DATA_PERSISTENCE with application name in litmus experiment.
sed -i '/name: DATA_PERSISTENCE/{n;s/.*/            value: busybox/}' run_percona_controller_nw_delay.yml

## Insert the set of variables for busybox data consistency util into configmap spec.
sed -i '/parameters.yml: |/a \
    dbuser: root \
    dbpassword: k8sDem0 \
    dbname: tdb
' run_percona_controller_nw_delay.yml

cat run_percona_controller_nw_delay.yml

bash ../openebs-konvoy-e2e/utils/litmus_job_runner label='name:percona-controller-nw-delay' job=run_percona_controller_nw_delay.yml
cd..

bash openebs-konvoy-e2e/utils/dump_cluster_state;
bash openebs-konvoy-e2e/utils/event_updater jobname:percona-controller-nw-delay $test_name jobid:"$job_id" pipeline_id:"$pipeline_id"

rc_val=$(echo $?)
current_time=$(eval $time)

if [ "$rc_val" != "0" ]; then
bash openebs-konvoy-e2e/utils/e2e-cr jobname:percona-controller-nw-delay jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" openebs_version:"$releaseTag" test_result:Fail
exit 1;
fi

bash openebs-konvoy-e2e/utils/e2e-cr jobname:percona-controller-nw-delay jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" openebs_version:"$releaseTag" test_result:Pass

if [ "$1" == "node" ];then
  node $2 $3 $4
else
  pod
fi
}
