#!/bin/bash
set -x

pod(){
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@ip -p $port 'cd e2e-konvoy && bash openebs-konvoy-e2e/pipelines/OpenEBS-base/stages/5-chaos/percona-target-nw-delay node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$RELEASE_TAG'"'
}

node(){
source ~/.profile
job_id=$(echo $1)
pipeline_id=$(echo $2)
releaseTag=$(echo $3)
time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

bash openebs-konvoy-e2e/utils/e2e-cr jobname:percona-target-nw-delay jobphase:Waiting
bash openebs-konvoy-e2e/utils/e2e-cr jobname:percona-target-nw-delay jobphase:Running init_time:"$current_time" job_id:"$job_id" pipeline_id:"$pipeline_id" openebs_version:"$releaseTag"

##############################
# Verifying Data-persistence #
##############################

test_name=$(bash openebs-konvoy-e2e/utils/generate_test_name testcase=data-persistence-check metadata="")
echo $test_name

cd litmus
echo "Running Litmus Book for verifying data-persistence against percona application."
cp experiments/functional/data-persistence/run_litmus_test.yml run_verify_data_persistence.yml

sed -i -e 's/generateName: data-persistence-litmus-/generateName: data-persistence-percona-cstor-/g' \
-e 's/name: litmus-data-persistence/name: data-persistence-percona-cstor/g' \
-e '/name: APP_NAMESPACE/{n;s/.*/            value: percona-cstor/}' \
-e '/name: APP_LABEL/{n;s/.*/            value: '\''name=percona'\''/}' \
-e '/name: STATUS/{n;s/.*/           value: VERIFY/}' \
-e '/name: DATA_PERSISTENCE/{n;s/.*/            value: mysql/}' run_verify_data_persistence.yml

## Insert the set of variables for percona data consistency util into configmap spec.
sed -i '/parameters.yml: |/a \
    dbuser: root \
    dbpassword: k8sDem0 \
    dbname: tdb
' run_verify_data_persistence.yml

cat run_verify_data_persistence.yml

bash openebs-konvoy-e2e/utils/litmus_job_runner label='name:data-persistence-percona-cstor' job=run_verify_data_persistence.yml
cd ..

bash openebs-konvoy-e2e/utils/dump_cluster_state;
bash openebs-konvoy-e2e/utils/event_updater jobname:percona-target-nw-delay $test_name jobid:"$job_id" pipeline_id:"$pipeline_id"


##############################################
# Delete Files after Verify Data-Persistence #
##############################################

test_name=$(bash openebs-konvoy-e2e/utils/generate_test_name testcase=data-persistence-check metadata="")
echo $test_name

cd litmus
cp experiments/functional/data-persistence/run_litmus_test.yml run_delete_data_files.yml

sed -i -e 's/generateName: data-persistence-litmus-/generateName: data-persistence-percona-cstor-/g' \
-e 's/name: litmus-data-persistence/name: data-persistence-percona-cstor/g' \
-e '/name: APP_NAMESPACE/{n;s/.*/            value: percona-cstor/}' \
-e '/name: APP_LABEL/{n;s/.*/            value: '\''name=percona'\''/}' \
-e '/name: STATUS/{n;s/.*/           value: DELETE/}' \
-e '/name: DATA_PERSISTENCE/{n;s/.*/            value: mysql/}' run_delete_data_files.yml

## Insert the set of variables for percona data consistency util into configmap spec.
sed -i '/parameters.yml: |/a \
    dbuser: root \
    dbpassword: k8sDem0 \
    dbname: tdb
' run_delete_data_files.yml

cat run_delete_data_files.yml

bash openebs-konvoy-e2e/utils/litmus_job_runner label='name:data-persistence-percona-cstor' job=run_verify_data_persistence.yml
cd ..

bash openebs-konvoy-e2e/utils/dump_cluster_state;
bash openebs-konvoy-e2e/utils/event_updater jobname:percona-target-nw-delay $test_name jobid:"$job_id" pipeline_id:"$pipeline_id"

##########################################
## Performing Target-network-delay test ##
##########################################

run_id="percona-cstor";test_name=$(bash openebs-konvoy-e2e/utils/generate_test_name testcase=openebs-target-network-delay metadata="")
echo $test_name

cd litmus
cp experiments/chaos/openebs_target_network_delay/run_litmus_test.yml run_percona_target_nw_delay.yml

sed -i -e 's/openebs-target-network-delay/percona-target-nw-delay/g' \
-e 's/name: target-failure/name: percona-target-failure-configmap/g' \
-e 's/value: app-percona-ns/value: percona-cstor/g' run_percona_target_nw_delay.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' run_percona_target_nw_delay.yml            

## Replace the value of DATA_PERSISTENCE with application name in litmus experiment.
sed -i '/name: DATA_PERSISTENCE/{n;s/.*/            value: busybox/}' run_percona_target_nw_delay.yml

## Insert the set of variables for busybox data consistency util into configmap spec.
sed -i '/parameters.yml: |/a \
    dbuser: root \
    dbpassword: k8sDem0 \
    dbname: tdb
' run_percona_target_nw_delay.yml

cat run_percona_target_nw_delay.yml

bash openebs-konvoy-e2e/utils/litmus_job_runner label='name:percona-target-nw-delay' job=run_percona_target_nw_delay.yml
cd..

bash openebs-konvoy-e2e/utils/dump_cluster_state;
bash openebs-konvoy-e2e/utils/event_updater jobname:percona-target-nw-delay $test_name jobid:"$job_id" pipeline_id:"$pipeline_id"

rc_val=$(echo $?)
current_time=$(eval $time)

if [ "$rc_val" != "0" ]; then
bash Openshift-EE/utils/e2e-cr jobname:percona-target-nw-delay jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" openebs_version:"$releaseTag" test_result:Fail
exit 1;
fi

bash Openshift-EE/utils/e2e-cr jobname:percona-target-nw-delay jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" openebs_version:"$releaseTag" test_result:Pass

if [ "$1" == "node" ];then
  node $2 $3 $4
else
  pod
fi
}
